# Generated by Django 4.0.5 on 2022-06-29 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Petrol', 'Petrol station'), ('Diesel', 'Diesel station'), ('Gas', 'Gas station'), ('Electric', 'Electric station')], max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
