# Generated by Django 4.0.5 on 2022-06-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_site_upload_sites_site_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='file',
        ),
    ]
