# Generated by Django 4.0.5 on 2022-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_remove_site_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='files',
            field=models.ManyToManyField(to='demoapp.upload'),
        ),
    ]
